# Generated by Django 3.2 on 2021-04-24 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField()),
                ('login', models.CharField(max_length=255)),
                ('avatar_url', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('html_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('html_url', models.CharField(max_length=255)),
                ('git_url', models.CharField(max_length=255)),
                ('ssh_url', models.CharField(max_length=255)),
                ('clone_url', models.CharField(max_length=255)),
                ('homepage', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('stargazers_count', models.PositiveIntegerField()),
                ('watchers_count', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=255)),
                ('forks_count', models.PositiveIntegerField()),
                ('forks', models.PositiveIntegerField()),
                ('open_issues', models.PositiveIntegerField()),
                ('watchers', models.PositiveIntegerField()),
                ('network_count', models.PositiveIntegerField()),
                ('subscribers_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.owners')),
            ],
        ),
    ]
